const fs = require('fs');
const path = require('path');

const mgmtDir = path.join(__dirname, 'src', 'pages', 'management');
if (!fs.existsSync(mgmtDir)) {
  fs.mkdirSync(mgmtDir, { recursive: true });
}

// 1. ROISavings.tsx
const roiCode = `import React from 'react';
import { motion } from 'framer-motion';
import { TrendingUp, BarChart2, DollarSign, Download, Percent, LineChart } from 'lucide-react';

export default function ROISavings() {
  return (
    <motion.div initial={{opacity:0}} animate={{opacity:1}} className="space-y-6 max-w-[1600px] mx-auto pb-12">
      <div className="flex justify-between items-start">
        <div>
          <div className="flex items-center gap-2 mb-2">
             <span className="text-[10px] font-bold tracking-widest uppercase bg-blue-50 text-blue-700 px-2 py-0.5 rounded border border-blue-200">Executive Financial Performance</span>
          </div>
          <h1 className="text-3xl font-black text-gray-900 tracking-tight leading-none mb-2">Logistics ROI & Savings</h1>
          <p className="text-xs text-gray-500 font-medium">Executive view of freight optimization, cost avoidance and financial impact generated by FreightIQ.</p>
        </div>
        <button className="bg-gray-900 text-white px-4 py-2.5 rounded-lg text-[10px] font-bold uppercase tracking-widest flex items-center gap-2 hover:bg-gray-800 transition-colors">
          <Download className="w-4 h-4"/> Export ROI Report
        </button>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-4">
        {[
          { label: "Total Logistics Spend", val: "₹48.2 Cr", icon: <DollarSign className="w-4 h-4"/>, color: "text-blue-600", bg: "bg-blue-50" },
          { label: "AI-Driven Savings", val: "₹4.12 Cr", icon: <TrendingUp className="w-4 h-4"/>, color: "text-green-600", bg: "bg-green-50" },
          { label: "Demurrage Saved", val: "₹89 L", icon: <BarChart2 className="w-4 h-4"/>, color: "text-green-600", bg: "bg-green-50" },
          { label: "Cost Avoidance", val: "₹2.84 Cr", icon: <LineChart className="w-4 h-4"/>, color: "text-blue-600", bg: "bg-blue-50" },
          { label: "FreightIQ ROI", val: "14.8x", icon: <Percent className="w-4 h-4"/>, color: "text-amber-600", bg: "bg-amber-50" },
          { label: "Budget Variance", val: "-8.4%", icon: <TrendingUp className="w-4 h-4"/>, color: "text-green-600", bg: "bg-green-50" },
        ].map((kpi, i) => (
          <motion.div key={i} className="bg-white p-4 rounded-xl border border-gray-200 shadow-sm flex flex-col justify-between" title="Demo / Simulated KPI Metric">
            <div className="flex justify-between items-start mb-3">
              <div className="text-[10px] font-bold text-gray-500 uppercase tracking-widest leading-tight">{kpi.label}</div>
              <div className={\`p-1.5 rounded-lg \${kpi.bg} \${kpi.color}\`}>{kpi.icon}</div>
            </div>
            <div className="text-2xl font-black text-gray-900 leading-none mb-1">{kpi.val}</div>
            <div className="text-[9px] font-bold text-gray-400 uppercase tracking-widest">Demo Data</div>
          </motion.div>
        ))}
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-12 gap-6">
         <div className="xl:col-span-8 bg-white rounded-xl border border-gray-200 shadow-sm p-6 flex flex-col">
            <div className="flex justify-between items-start mb-6">
               <div>
                  <h2 className="text-sm font-black text-gray-900 uppercase tracking-widest mb-1">Cumulative Savings vs Unoptimized Benchmark</h2>
                  <p className="text-[11px] font-medium text-gray-500">FreightIQ Optimized Spend vs Baseline</p>
               </div>
               <div className="flex items-center gap-3 text-[9px] font-bold uppercase tracking-widest text-gray-500">
                  <div className="flex items-center gap-1.5"><div className="w-3 h-0.5 bg-gray-400"></div> Benchmark</div>
                  <div className="flex items-center gap-1.5"><div className="w-3 h-0.5 bg-green-500"></div> Actual Spend</div>
               </div>
            </div>
            
            <div className="flex-1 min-h-[300px] bg-gray-50 rounded-lg border border-gray-100 flex items-center justify-center relative overflow-hidden">
               {/* SVG Chart representation */}
               <div className="absolute left-10 right-0 top-6 bottom-10">
                 <svg className="w-full h-full overflow-visible" preserveAspectRatio="none" viewBox="0 0 100 100">
                    {/* Benchmark */}
                    <path d="M 0,90 L 33,60 L 66,35 L 100,10" fill="none" stroke="#9CA3AF" strokeWidth="2" strokeDasharray="4,4" />
                    {/* Actual */}
                    <path d="M 0,90 L 33,65 L 66,45 L 100,25" fill="none" stroke="#22C55E" strokeWidth="3" />
                    {/* Savings Gap shading */}
                    <path d="M 0,90 L 33,60 L 66,35 L 100,10 L 100,25 L 66,45 L 33,65 Z" fill="#22C55E" stroke="none" opacity="0.1" />
                 </svg>
                 <div className="absolute right-0 top-[15%] transform translate-x-2">
                   <span className="text-[10px] font-bold text-green-700 bg-green-50 px-1 border border-green-200 rounded">Gap: ₹4.12 Cr</span>
                 </div>
               </div>
               <div className="absolute bottom-4 w-full flex justify-around text-[10px] font-bold text-gray-400 pl-10 pr-4">
                  <span>Q1</span><span>Q2</span><span>Q3</span><span>Q4</span>
               </div>
            </div>
            
            <div className="mt-4 text-center">
               <p className="text-[11px] text-gray-600 font-medium">By Q4, actual spend tracking generated a cumulative savings gap of ₹4.12 Cr against the unoptimized spot market benchmark. <span className="font-bold text-gray-400 text-[10px] uppercase">(Simulated Data)</span></p>
            </div>
         </div>

         <div className="xl:col-span-4 space-y-6">
            <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-6">
               <h2 className="text-sm font-black text-gray-900 uppercase tracking-widest mb-4">FreightIQ ROI</h2>
               <div className="space-y-4">
                  <div className="flex justify-between items-center border-b border-gray-100 pb-2">
                     <span className="text-xs font-semibold text-gray-600">Technology Investment</span>
                     <span className="font-mono font-bold text-gray-900 text-sm">₹28 L</span>
                  </div>
                  <div className="flex justify-between items-center border-b border-gray-100 pb-2">
                     <span className="text-xs font-semibold text-gray-600">Savings Generated</span>
                     <span className="font-mono font-bold text-green-600 text-sm">₹4.12 Cr</span>
                  </div>
                  <div className="flex justify-between items-center border-b border-gray-100 pb-2">
                     <span className="text-xs font-semibold text-gray-600">Net Benefit</span>
                     <span className="font-mono font-black text-gray-900 text-lg">₹3.84 Cr</span>
                  </div>
                  <div className="flex justify-between items-center bg-gray-50 p-3 rounded-lg border border-gray-100">
                     <span className="text-xs font-black text-gray-900">ROI Multiple</span>
                     <span className="font-mono font-black text-amber-600 text-2xl">14.8x</span>
                  </div>
               </div>
               <div className="mt-3 text-right">
                  <span className="text-[9px] font-bold text-gray-400 uppercase tracking-widest">Demo Calculation</span>
               </div>
            </div>

            <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-6">
               <h2 className="text-sm font-black text-gray-900 uppercase tracking-widest mb-4">Savings Breakdown</h2>
               <div className="space-y-3">
                  <div className="bg-gray-50 p-3 rounded-lg">
                     <div className="flex justify-between text-xs mb-1">
                        <span className="font-bold text-gray-900">Spot Avoidance</span>
                        <span className="font-mono font-bold text-green-600">₹2.8 Cr</span>
                     </div>
                     <div className="w-full bg-gray-200 h-1.5 rounded-full overflow-hidden">
                        <div className="bg-green-500 h-full" style={{width: '68%'}}></div>
                     </div>
                  </div>
                  <div className="bg-gray-50 p-3 rounded-lg">
                     <div className="flex justify-between text-xs mb-1">
                        <span className="font-bold text-gray-900">Demurrage Reduction</span>
                        <span className="font-mono font-bold text-green-600">₹89 L</span>
                     </div>
                     <div className="w-full bg-gray-200 h-1.5 rounded-full overflow-hidden">
                        <div className="bg-green-500 h-full" style={{width: '21%'}}></div>
                     </div>
                  </div>
                  <div className="bg-gray-50 p-3 rounded-lg">
                     <div className="flex justify-between text-xs mb-1">
                        <span className="font-bold text-gray-900">Fuel Optimization</span>
                        <span className="font-mono font-bold text-green-600">₹43 L</span>
                     </div>
                     <div className="w-full bg-gray-200 h-1.5 rounded-full overflow-hidden">
                        <div className="bg-green-500 h-full" style={{width: '11%'}}></div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
    </motion.div>
  );
}
`;
fs.writeFileSync(path.join(mgmtDir, 'ROISavings.tsx'), roiCode);


// 2. Performance.tsx
const perfCode = `import React from 'react';
import { motion } from 'framer-motion';
import { Activity, Anchor, Ship, Clock } from 'lucide-react';

export default function Performance() {
  return (
    <motion.div initial={{opacity:0}} animate={{opacity:1}} className="space-y-6 max-w-[1600px] mx-auto pb-12">
      <div>
        <div className="flex items-center gap-2 mb-2">
           <span className="text-[10px] font-bold tracking-widest uppercase bg-blue-50 text-blue-700 px-2 py-0.5 rounded border border-blue-200">Operational Performance Intelligence</span>
        </div>
        <h1 className="text-3xl font-black text-gray-900 tracking-tight leading-none mb-2">Logistics Performance</h1>
        <p className="text-xs text-gray-500 font-medium">Executive monitoring of fleet utilization, voyage efficiency, port turnaround and cargo delivery performance.</p>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-4">
        {[
          { label: "Vessel Utilization", val: "94.6%", icon: <Ship className="w-4 h-4"/>, color: "text-blue-600", bg: "bg-blue-50" },
          { label: "Berth Dwell Time", val: "38.4 hrs", icon: <Anchor className="w-4 h-4"/>, color: "text-green-600", bg: "bg-green-50" },
          { label: "Cargo Delivery SLA", val: "99.1%", icon: <Activity className="w-4 h-4"/>, color: "text-green-600", bg: "bg-green-50" },
          { label: "Avg Port Turnaround", val: "1.8 days", icon: <Clock className="w-4 h-4"/>, color: "text-blue-600", bg: "bg-blue-50" },
          { label: "Charter Efficiency", val: "92.4%", icon: <Activity className="w-4 h-4"/>, color: "text-amber-600", bg: "bg-amber-50" },
          { label: "Demurrage Reduction", val: "-22%", icon: <TrendingUp className="w-4 h-4"/>, color: "text-green-600", bg: "bg-green-50" },
        ].map((kpi, i) => (
          <motion.div key={i} className="bg-white p-4 rounded-xl border border-gray-200 shadow-sm">
            <div className="flex justify-between items-start mb-3">
              <div className="text-[10px] font-bold text-gray-500 uppercase tracking-widest leading-tight">{kpi.label}</div>
              <div className={\`p-1.5 rounded-lg \${kpi.bg} \${kpi.color}\`}>{kpi.icon}</div>
            </div>
            <div className="text-2xl font-black text-gray-900 leading-none mb-1">{kpi.val}</div>
          </motion.div>
        ))}
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
         <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-6">
            <h2 className="text-sm font-black text-gray-900 uppercase tracking-widest mb-4">East Coast Port Performance</h2>
            <div className="overflow-x-auto">
               <table className="w-full text-left border-collapse">
                  <thead>
                     <tr className="bg-gray-50 border-b border-gray-100">
                        <th className="py-2 px-3 text-[9px] font-bold text-gray-500 uppercase tracking-widest">Port</th>
                        <th className="py-2 px-3 text-[9px] font-bold text-gray-500 uppercase tracking-widest">Turnaround</th>
                        <th className="py-2 px-3 text-[9px] font-bold text-gray-500 uppercase tracking-widest">On-Time %</th>
                        <th className="py-2 px-3 text-[9px] font-bold text-gray-500 uppercase tracking-widest">Congestion</th>
                     </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-50">
                     <tr>
                        <td className="py-3 px-3 text-xs font-bold text-gray-900">Paradip</td>
                        <td className="py-3 px-3 text-xs font-mono font-bold text-gray-900">1.9d</td>
                        <td className="py-3 px-3 text-xs font-mono font-bold text-gray-900">92%</td>
                        <td className="py-3 px-3"><span className="bg-amber-50 text-amber-700 px-2 py-0.5 rounded text-[9px] font-bold uppercase tracking-widest">MODERATE</span></td>
                     </tr>
                     <tr>
                        <td className="py-3 px-3 text-xs font-bold text-gray-900">Visakhapatnam</td>
                        <td className="py-3 px-3 text-xs font-mono font-bold text-gray-900">1.6d</td>
                        <td className="py-3 px-3 text-xs font-mono font-bold text-gray-900">98%</td>
                        <td className="py-3 px-3"><span className="bg-green-50 text-green-700 px-2 py-0.5 rounded text-[9px] font-bold uppercase tracking-widest">LOW</span></td>
                     </tr>
                     <tr>
                        <td className="py-3 px-3 text-xs font-bold text-gray-900">Haldia</td>
                        <td className="py-3 px-3 text-xs font-mono font-bold text-gray-900">2.4d</td>
                        <td className="py-3 px-3 text-xs font-mono font-bold text-gray-900">86%</td>
                        <td className="py-3 px-3"><span className="bg-red-50 text-red-700 px-2 py-0.5 rounded text-[9px] font-bold uppercase tracking-widest">HIGH</span></td>
                     </tr>
                  </tbody>
               </table>
            </div>
         </div>

         <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-6">
            <h2 className="text-sm font-black text-gray-900 uppercase tracking-widest mb-4">Performance Trend</h2>
            <div className="space-y-4">
               <div className="flex items-center justify-between bg-gray-50 p-3 rounded-lg border border-gray-100">
                  <span className="text-xs font-bold text-gray-900">Cost Efficiency</span>
                  <span className="text-[10px] font-bold uppercase tracking-widest text-green-600 flex items-center gap-1">↑ Improved (Demo)</span>
               </div>
               <div className="flex items-center justify-between bg-gray-50 p-3 rounded-lg border border-gray-100">
                  <span className="text-xs font-bold text-gray-900">Vessel Utilization</span>
                  <span className="text-[10px] font-bold uppercase tracking-widest text-green-600 flex items-center gap-1">↑ Improved (Demo)</span>
               </div>
               <div className="flex items-center justify-between bg-gray-50 p-3 rounded-lg border border-gray-100">
                  <span className="text-xs font-bold text-gray-900">Delivery SLA</span>
                  <span className="text-[10px] font-bold uppercase tracking-widest text-gray-500 flex items-center gap-1">→ Stable (Demo)</span>
               </div>
               <div className="flex items-center justify-between bg-gray-50 p-3 rounded-lg border border-gray-100">
                  <span className="text-xs font-bold text-gray-900">Port Turnaround</span>
                  <span className="text-[10px] font-bold uppercase tracking-widest text-amber-600 flex items-center gap-1">↓ Declined (Demo)</span>
               </div>
            </div>
         </div>
      </div>
    </motion.div>
  );
}
`;
fs.writeFileSync(path.join(mgmtDir, 'Performance.tsx'), perfCode);


// 3. AuditLogs.tsx
const auditCode = `import React from 'react';
import { motion } from 'framer-motion';
import { FileText, Download, CheckCircle2, ShieldAlert } from 'lucide-react';

export default function AuditLogs() {
  return (
    <motion.div initial={{opacity:0}} animate={{opacity:1}} className="space-y-6 max-w-[1600px] mx-auto pb-12">
      <div className="flex justify-between items-start">
        <div>
          <div className="flex items-center gap-2 mb-2">
             <span className="text-[10px] font-bold tracking-widest uppercase bg-blue-50 text-blue-700 px-2 py-0.5 rounded border border-blue-200">Decision Traceability & Audit</span>
          </div>
          <h1 className="text-3xl font-black text-gray-900 tracking-tight leading-none mb-2">Audit Logs</h1>
          <p className="text-xs text-gray-500 font-medium">Traceable record of decisions, approvals, system actions and governance events.</p>
        </div>
        <button className="bg-gray-900 text-white px-4 py-2.5 rounded-lg text-[10px] font-bold uppercase tracking-widest flex items-center gap-2 hover:bg-gray-800 transition-colors">
          <Download className="w-4 h-4"/> Export Audit Logs
        </button>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
         <div className="bg-white p-5 rounded-xl border border-gray-200 shadow-sm flex flex-col justify-between">
            <div className="text-[10px] font-bold text-gray-500 uppercase tracking-widest mb-2">Total Events (30d)</div>
            <div className="text-3xl font-black text-gray-900">328</div>
         </div>
         <div className="bg-white p-5 rounded-xl border border-gray-200 shadow-sm flex flex-col justify-between">
            <div className="text-[10px] font-bold text-gray-500 uppercase tracking-widest mb-2">Today</div>
            <div className="text-3xl font-black text-gray-900">18</div>
         </div>
         <div className="bg-white p-5 rounded-xl border border-gray-200 shadow-sm flex flex-col justify-between">
            <div className="text-[10px] font-bold text-gray-500 uppercase tracking-widest mb-2">Policy Checks Passed</div>
            <div className="text-3xl font-black text-green-600 flex items-center gap-2">97.8% <CheckCircle2 className="w-5 h-5"/></div>
         </div>
         <div className="bg-white p-5 rounded-xl border border-gray-200 shadow-sm flex flex-col justify-between border-l-4 border-l-amber-500">
            <div className="text-[10px] font-bold text-gray-500 uppercase tracking-widest mb-2">Events Requiring Review</div>
            <div className="text-3xl font-black text-amber-600 flex items-center gap-2">04 <ShieldAlert className="w-5 h-5"/></div>
         </div>
      </div>

      <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden flex flex-col">
         <div className="p-4 border-b border-gray-100 bg-gray-50/50 flex flex-wrap gap-3 items-center">
            <input type="text" placeholder="Search Request ID, Actor..." className="border border-gray-200 rounded-lg px-3 py-1.5 text-xs outline-none focus:border-blue-500"/>
            <select className="border border-gray-200 rounded-lg px-3 py-1.5 text-xs outline-none text-gray-600 font-bold uppercase tracking-widest">
               <option>All Modules</option>
               <option>Decision Maker</option>
               <option>Operations</option>
               <option>Analyst</option>
            </select>
            <select className="border border-gray-200 rounded-lg px-3 py-1.5 text-xs outline-none text-gray-600 font-bold uppercase tracking-widest">
               <option>All Status</option>
               <option>Passed</option>
               <option>Review</option>
            </select>
         </div>
         <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse min-w-[1000px]">
               <thead>
                  <tr className="bg-white border-b border-gray-100">
                     <th className="py-3 px-4 text-[9px] font-bold text-gray-500 uppercase tracking-widest">Timestamp</th>
                     <th className="py-3 px-4 text-[9px] font-bold text-gray-500 uppercase tracking-widest">Actor</th>
                     <th className="py-3 px-4 text-[9px] font-bold text-gray-500 uppercase tracking-widest">Role</th>
                     <th className="py-3 px-4 text-[9px] font-bold text-gray-500 uppercase tracking-widest">Action</th>
                     <th className="py-3 px-4 text-[9px] font-bold text-gray-500 uppercase tracking-widest">Module</th>
                     <th className="py-3 px-4 text-[9px] font-bold text-gray-500 uppercase tracking-widest">Req ID</th>
                     <th className="py-3 px-4 text-[9px] font-bold text-gray-500 uppercase tracking-widest text-right">Status</th>
                  </tr>
               </thead>
               <tbody className="divide-y divide-gray-50">
                  <tr className="hover:bg-gray-50 cursor-pointer">
                     <td className="py-4 px-4 text-[10px] font-mono text-gray-500">12 Oct 2026 14:22</td>
                     <td className="py-4 px-4 text-xs font-bold text-gray-900">D. Chen</td>
                     <td className="py-4 px-4 text-[10px] font-medium text-gray-600">Chartering Manager</td>
                     <td className="py-4 px-4 text-xs font-bold text-gray-900">Contract Approved</td>
                     <td className="py-4 px-4 text-[10px] font-medium text-gray-600">Decision Maker</td>
                     <td className="py-4 px-4 text-xs font-mono font-bold text-gray-900">REQ-MO-2026-88</td>
                     <td className="py-4 px-4 text-right"><span className="bg-green-50 border border-green-200 text-green-700 px-2 py-0.5 rounded text-[9px] font-bold uppercase tracking-widest">✓ PASSED</span></td>
                  </tr>
                  <tr className="hover:bg-gray-50 cursor-pointer">
                     <td className="py-4 px-4 text-[10px] font-mono text-gray-500">11 Oct 2026 09:00</td>
                     <td className="py-4 px-4 text-xs font-bold text-gray-900">System</td>
                     <td className="py-4 px-4 text-[10px] font-medium text-gray-600">AI Model</td>
                     <td className="py-4 px-4 text-xs font-bold text-gray-900">Model Recalibration</td>
                     <td className="py-4 px-4 text-[10px] font-medium text-gray-600">Analyst</td>
                     <td className="py-4 px-4 text-xs font-mono font-bold text-gray-900">MODEL-v4.2</td>
                     <td className="py-4 px-4 text-right"><span className="bg-blue-50 border border-blue-200 text-blue-700 px-2 py-0.5 rounded text-[9px] font-bold uppercase tracking-widest">VERIFIED</span></td>
                  </tr>
                  <tr className="hover:bg-gray-50 cursor-pointer">
                     <td className="py-4 px-4 text-[10px] font-mono text-gray-500">10 Oct 2026 18:45</td>
                     <td className="py-4 px-4 text-xs font-bold text-gray-900">A. Sharma</td>
                     <td className="py-4 px-4 text-[10px] font-medium text-gray-600">Operations Lead</td>
                     <td className="py-4 px-4 text-xs font-bold text-gray-900">Spot Override</td>
                     <td className="py-4 px-4 text-[10px] font-medium text-gray-600">Operations</td>
                     <td className="py-4 px-4 text-xs font-mono font-bold text-gray-900">REQ-MO-2026-82</td>
                     <td className="py-4 px-4 text-right"><span className="bg-amber-50 border border-amber-200 text-amber-700 px-2 py-0.5 rounded text-[9px] font-bold uppercase tracking-widest">⚠ REVIEW</span></td>
                  </tr>
               </tbody>
            </table>
         </div>
      </div>
    </motion.div>
  );
}
`;
fs.writeFileSync(path.join(mgmtDir, 'AuditLogs.tsx'), auditCode);

// 4. Governance.tsx
const govCode = `import React from 'react';
import { motion } from 'framer-motion';
import { ShieldAlert, Download, CheckCircle2, AlertTriangle } from 'lucide-react';

export default function Governance() {
  return (
    <motion.div initial={{opacity:0}} animate={{opacity:1}} className="space-y-6 max-w-[1600px] mx-auto pb-12">
      <div className="flex justify-between items-start">
        <div>
          <div className="flex items-center gap-2 mb-2">
             <span className="text-[10px] font-bold tracking-widest uppercase bg-blue-50 text-blue-700 px-2 py-0.5 rounded border border-blue-200">Governance, Privacy & Policy</span>
          </div>
          <h1 className="text-3xl font-black text-gray-900 tracking-tight leading-none mb-2">Governance & Compliance</h1>
          <p className="text-xs text-gray-500 font-medium">Monitor privacy, security, accessibility, policy adherence and responsible use of FreightIQ.</p>
        </div>
        <button className="bg-gray-900 text-white px-4 py-2.5 rounded-lg text-[10px] font-bold uppercase tracking-widest flex items-center gap-2 hover:bg-gray-800 transition-colors">
          <Download className="w-4 h-4"/> Download Governance Report
        </button>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
         <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-sm">
            <div className="text-[10px] font-bold text-gray-500 uppercase tracking-widest mb-1">Policy Adherence</div>
            <div className="text-2xl font-black text-gray-900">98.4%</div>
         </div>
         <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-sm">
            <div className="text-[10px] font-bold text-gray-500 uppercase tracking-widest mb-1">Privacy Controls</div>
            <div className="text-sm font-black text-green-600 mt-2 flex items-center gap-1"><CheckCircle2 className="w-4 h-4"/> OPERATIONAL</div>
         </div>
         <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-sm">
            <div className="text-[10px] font-bold text-gray-500 uppercase tracking-widest mb-1">Audit Coverage</div>
            <div className="text-2xl font-black text-gray-900">100%</div>
         </div>
         <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-sm border-l-4 border-l-amber-500">
            <div className="text-[10px] font-bold text-gray-500 uppercase tracking-widest mb-1">Open Reviews</div>
            <div className="text-2xl font-black text-amber-600">03</div>
         </div>
         <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-sm">
            <div className="text-[10px] font-bold text-gray-500 uppercase tracking-widest mb-1">Accessibility Status</div>
            <div className="text-sm font-black text-blue-600 mt-2">WCAG 2.1 AA</div>
         </div>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-12 gap-6">
         {/* DPDP Privacy Center */}
         <div className="xl:col-span-8 space-y-6">
            <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-6">
               <h2 className="text-sm font-black text-gray-900 uppercase tracking-widest mb-4">DPDP Privacy Controls</h2>
               <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-4">
                  <div className="bg-gray-50 p-3 rounded-lg border border-gray-100">
                     <div className="text-[10px] font-bold text-gray-500 uppercase tracking-widest mb-1">Data Minimization</div>
                     <div className="text-[11px] font-bold text-green-600 flex items-center gap-1"><CheckCircle2 className="w-3 h-3"/> Active</div>
                  </div>
                  <div className="bg-gray-50 p-3 rounded-lg border border-gray-100">
                     <div className="text-[10px] font-bold text-gray-500 uppercase tracking-widest mb-1">Purpose Limitation</div>
                     <div className="text-[11px] font-bold text-green-600 flex items-center gap-1"><CheckCircle2 className="w-3 h-3"/> Active</div>
                  </div>
                  <div className="bg-gray-50 p-3 rounded-lg border border-gray-100">
                     <div className="text-[10px] font-bold text-gray-500 uppercase tracking-widest mb-1">Consent Mgmt</div>
                     <div className="text-[11px] font-bold text-green-600 flex items-center gap-1"><CheckCircle2 className="w-3 h-3"/> Operational</div>
                  </div>
                  <div className="bg-gray-50 p-3 rounded-lg border border-gray-100">
                     <div className="text-[10px] font-bold text-gray-500 uppercase tracking-widest mb-1">Data Retention</div>
                     <div className="text-[11px] font-bold text-blue-600 flex items-center gap-1"><ShieldAlert className="w-3 h-3"/> Monitored</div>
                  </div>
               </div>
               <div className="grid grid-cols-4 gap-4 border-t border-gray-50 pt-4">
                  <div>
                     <span className="text-[9px] font-bold text-gray-500 uppercase tracking-widest block mb-1">Access Requests</span>
                     <span className="text-xs font-bold text-gray-900">02 Pending</span>
                  </div>
                  <div>
                     <span className="text-[9px] font-bold text-gray-500 uppercase tracking-widest block mb-1">Correction</span>
                     <span className="text-xs font-bold text-gray-900">01 Pending</span>
                  </div>
                  <div>
                     <span className="text-[9px] font-bold text-gray-500 uppercase tracking-widest block mb-1">Erasure</span>
                     <span className="text-xs font-bold text-gray-900">01 Pending</span>
                  </div>
                  <div>
                     <span className="text-[9px] font-bold text-gray-500 uppercase tracking-widest block mb-1">Grievances</span>
                     <span className="text-xs font-bold text-gray-400">00 Open</span>
                  </div>
               </div>
               <div className="mt-4 pt-4 border-t border-gray-50 text-right">
                  <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest italic">Designed with DPDP privacy principles.</span>
               </div>
            </div>

            <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-6">
               <h2 className="text-sm font-black text-gray-900 uppercase tracking-widest mb-4">Role-Based Access Control</h2>
               <div className="space-y-3">
                  <div className="bg-gray-50 p-4 rounded-lg border border-gray-100 flex justify-between items-center">
                     <div>
                        <div className="text-xs font-bold text-gray-900 mb-1">Operations</div>
                        <div className="text-[10px] font-medium text-gray-500">Access: Operational</div>
                     </div>
                     <div className="text-right">
                        <div className="text-[9px] font-bold text-gray-400 uppercase tracking-widest">Approval Authority</div>
                        <div className="text-[11px] font-bold text-gray-900">None</div>
                     </div>
                  </div>
                  <div className="bg-gray-50 p-4 rounded-lg border border-gray-100 flex justify-between items-center">
                     <div>
                        <div className="text-xs font-bold text-gray-900 mb-1">Analyst</div>
                        <div className="text-[10px] font-medium text-gray-500">Access: Forecasting & Simulation</div>
                     </div>
                     <div className="text-right">
                        <div className="text-[9px] font-bold text-gray-400 uppercase tracking-widest">Approval Authority</div>
                        <div className="text-[11px] font-bold text-gray-900">None</div>
                     </div>
                  </div>
                  <div className="bg-gray-50 p-4 rounded-lg border border-gray-100 flex justify-between items-center border-l-4 border-l-blue-500">
                     <div>
                        <div className="text-xs font-bold text-gray-900 mb-1">Decision Maker</div>
                        <div className="text-[10px] font-medium text-gray-500">Access: Chartering & Approval</div>
                     </div>
                     <div className="text-right">
                        <div className="text-[9px] font-bold text-gray-400 uppercase tracking-widest">Approval Authority</div>
                        <div className="text-[11px] font-bold text-blue-700">Contract Execution</div>
                     </div>
                  </div>
                  <div className="bg-gray-50 p-4 rounded-lg border border-gray-100 flex justify-between items-center border-l-4 border-l-gray-900">
                     <div>
                        <div className="text-xs font-bold text-gray-900 mb-1">Management</div>
                        <div className="text-[10px] font-medium text-gray-500">Access: Executive & Governance</div>
                     </div>
                     <div className="text-right">
                        <div className="text-[9px] font-bold text-gray-400 uppercase tracking-widest">Approval Authority</div>
                        <div className="text-[11px] font-bold text-gray-900">Policy & Audit</div>
                     </div>
                  </div>
               </div>
            </div>
         </div>

         {/* Sidebar Policies */}
         <div className="xl:col-span-4 space-y-6">
            <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-6">
               <h2 className="text-sm font-black text-gray-900 uppercase tracking-widest mb-4">GIGW 3.0 / Accessibility</h2>
               <div className="space-y-3 text-xs">
                  <div className="flex justify-between items-center border-b border-gray-100 pb-2">
                     <span className="font-semibold text-gray-700">WCAG 2.1 AA</span>
                     <span className="font-bold text-blue-600 flex items-center gap-1"><CheckCircle2 className="w-3 h-3"/> Targeted</span>
                  </div>
                  <div className="flex justify-between items-center border-b border-gray-100 pb-2">
                     <span className="font-semibold text-gray-700">Keyboard Navigation</span>
                     <span className="font-bold text-green-600 flex items-center gap-1"><CheckCircle2 className="w-3 h-3"/> Active</span>
                  </div>
                  <div className="flex justify-between items-center border-b border-gray-100 pb-2">
                     <span className="font-semibold text-gray-700">Screen Reader Support</span>
                     <span className="font-bold text-green-600 flex items-center gap-1"><CheckCircle2 className="w-3 h-3"/> Active</span>
                  </div>
                  <div className="flex justify-between items-center border-b border-gray-100 pb-2">
                     <span className="font-semibold text-gray-700">Color Contrast</span>
                     <span className="font-bold text-green-600 flex items-center gap-1"><CheckCircle2 className="w-3 h-3"/> Verified</span>
                  </div>
                  <div className="flex justify-between items-center border-b border-gray-100 pb-2">
                     <span className="font-semibold text-gray-700">Text Alternatives</span>
                     <span className="font-bold text-green-600 flex items-center gap-1"><CheckCircle2 className="w-3 h-3"/> Active</span>
                  </div>
                  <div className="flex justify-between items-center border-b border-gray-100 pb-2">
                     <span className="font-semibold text-gray-700">Accessible Charts</span>
                     <span className="font-bold text-green-600 flex items-center gap-1"><CheckCircle2 className="w-3 h-3"/> Active</span>
                  </div>
                  <div className="flex justify-between items-center">
                     <span className="font-semibold text-gray-700">Reduced Motion</span>
                     <span className="font-bold text-green-600 flex items-center gap-1"><CheckCircle2 className="w-3 h-3"/> Supported</span>
                  </div>
               </div>
            </div>

            <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-6">
               <h2 className="text-sm font-black text-gray-900 uppercase tracking-widest mb-4">Security & Data Governance</h2>
               <div className="space-y-3 text-xs">
                  <div className="flex justify-between items-center border-b border-gray-100 pb-2">
                     <span className="font-semibold text-gray-700">Authentication</span>
                     <span className="font-bold text-green-600 flex items-center gap-1"><CheckCircle2 className="w-3 h-3"/> Operational</span>
                  </div>
                  <div className="flex justify-between items-center border-b border-gray-100 pb-2">
                     <span className="font-semibold text-gray-700">Audit Trail</span>
                     <span className="font-bold text-blue-600 flex items-center gap-1"><CheckCircle2 className="w-3 h-3"/> Immutable</span>
                  </div>
                  <div className="flex justify-between items-center border-b border-gray-100 pb-2">
                     <span className="font-semibold text-gray-700">Data Encryption</span>
                     <span className="font-bold text-green-600 flex items-center gap-1"><CheckCircle2 className="w-3 h-3"/> Protected</span>
                  </div>
                  <div className="flex justify-between items-center border-b border-gray-100 pb-2">
                     <span className="font-semibold text-gray-700">Export Controls</span>
                     <span className="font-bold text-green-600 flex items-center gap-1"><CheckCircle2 className="w-3 h-3"/> Enabled</span>
                  </div>
                  <div className="flex justify-between items-center">
                     <span className="font-semibold text-gray-700">Session Security</span>
                     <span className="font-bold text-green-600 flex items-center gap-1"><CheckCircle2 className="w-3 h-3"/> Active</span>
                  </div>
               </div>
            </div>
         </div>
      </div>
    </motion.div>
  );
}
`;
fs.writeFileSync(path.join(mgmtDir, 'Governance.tsx'), govCode);

// Add routing in App.tsx
const appFile = path.join(__dirname, 'src', 'App.tsx');
let appContent = fs.readFileSync(appFile, 'utf8');

if (!appContent.includes('ROISavings')) {
  appContent = appContent.replace("import Dashboard from './pages/Dashboard';",
`import Dashboard from './pages/Dashboard';
import ManagementDashboard from './components/dashboards/ManagementDashboard';
import ROISavings from './pages/management/ROISavings';
import Performance from './pages/management/Performance';
import AuditLogs from './pages/management/AuditLogs';
import Governance from './pages/management/Governance';`);
  
  appContent = appContent.replace("<Route path='/dashboard'",
`<Route path='/management/dashboard' element={<ProtectedRoute><motion.div {...pageTransition}><ManagementDashboard /></motion.div></ProtectedRoute>} />
        <Route path='/management/roi' element={<ProtectedRoute><motion.div {...pageTransition}><ROISavings /></motion.div></ProtectedRoute>} />
        <Route path='/management/performance' element={<ProtectedRoute><motion.div {...pageTransition}><Performance /></motion.div></ProtectedRoute>} />
        <Route path='/management/audit-logs' element={<ProtectedRoute><motion.div {...pageTransition}><AuditLogs /></motion.div></ProtectedRoute>} />
        <Route path='/management/governance' element={<ProtectedRoute><motion.div {...pageTransition}><Governance /></motion.div></ProtectedRoute>} />
        <Route path='/dashboard'`);
  
  fs.writeFileSync(appFile, appContent);
}

// Modify AppLayout.tsx Nav Items
const appLayoutFile = path.join(__dirname, 'src', 'components', 'AppLayout.tsx');
let layoutContent = fs.readFileSync(appLayoutFile, 'utf8');

if (layoutContent.includes("path: '/roi-savings'")) {
  layoutContent = layoutContent.replace("case 'Management':\n        return [\n          { path: '/dashboard', icon: <LayoutDashboard className=\"w-5 h-5\" />, label: 'Overview' },\n          { path: '/roi-savings', icon: <BarChart2 className=\"w-5 h-5\" />, label: 'ROI & Savings' },\n          { path: '/performance', icon: <Activity className=\"w-5 h-5\" />, label: 'Performance' },\n          { path: '/audit-logs', icon: <FileText className=\"w-5 h-5\" />, label: 'Audit Logs' },\n          { path: '/governance', icon: <ShieldAlert className=\"w-5 h-5\" />, label: 'Governance' },\n        ];", 
  "case 'Management':\n        return [\n          { path: '/management/dashboard', icon: <LayoutDashboard className=\"w-5 h-5\" />, label: 'Overview' },\n          { path: '/management/roi', icon: <BarChart2 className=\"w-5 h-5\" />, label: 'ROI & Savings' },\n          { path: '/management/performance', icon: <Activity className=\"w-5 h-5\" />, label: 'Performance' },\n          { path: '/management/audit-logs', icon: <FileText className=\"w-5 h-5\" />, label: 'Audit Logs' },\n          { path: '/management/governance', icon: <ShieldAlert className=\"w-5 h-5\" />, label: 'Governance' },\n        ];");
  
  layoutContent = layoutContent.replace("if(r === 'Decision Maker') navigate('/decision-maker/dashboard'); else navigate('/dashboard');", 
  "if(r === 'Decision Maker') navigate('/decision-maker/dashboard'); else if(r === 'Management') navigate('/management/dashboard'); else navigate('/dashboard');");
  
  fs.writeFileSync(appLayoutFile, layoutContent);
}

// Modify Dashboard.tsx to route Management to /management/dashboard
const dashboardFile = path.join(__dirname, 'src', 'pages', 'Dashboard.tsx');
let dashboardContent = fs.readFileSync(dashboardFile, 'utf8');
if (!dashboardContent.includes("Navigate to='/management/dashboard'")) {
  dashboardContent = dashboardContent.replace("case 'Management':", 
  "case 'Management':\n      return <Navigate to='/management/dashboard' replace />;\n    // case 'Management' fallthrough removed");
  // We remove the direct rendering of ManagementDashboard in Dashboard.tsx
  dashboardContent = dashboardContent.replace("return <ManagementDashboard />;", "");
  fs.writeFileSync(dashboardFile, dashboardContent);
}

console.log('Management module pages generated and hooked up correctly.');
