import React from 'react';
import { motion } from 'framer-motion';
import { TrendingUp, BarChart2, DollarSign, Download, Percent, LineChart } from 'lucide-react';

export default function ROISavings() {
  return (
    <motion.div initial={{opacity:0}} animate={{opacity:1}} className="space-y-6 max-w-[1600px] mx-auto pb-12">
      <div className="flex justify-between items-start">
        <div>
          <div className="flex items-center gap-2 mb-2">
             <span className="text-[10px] font-bold tracking-widest uppercase bg-blue-50 text-blue-700 px-2 py-0.5 rounded border border-blue-200">Executive Financial Performance</span>
          </div>
          <h1 className="text-3xl font-black text-gray-900 tracking-tight leading-none mb-2">Logistics ROI & Savings</h1>
          <p className="text-xs text-gray-500 font-medium">Executive view of freight optimization, cost avoidance and financial impact generated by FreightIQ.</p>
        </div>
        <button className="bg-gray-900 text-white px-4 py-2.5 rounded-lg text-[10px] font-bold uppercase tracking-widest flex items-center gap-2 hover:bg-gray-800 transition-colors">
          <Download className="w-4 h-4"/> Export ROI Report
        </button>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-4">
        {[
          { label: "Total Logistics Spend", val: "₹48.2 Cr", icon: <DollarSign className="w-4 h-4"/>, color: "text-blue-600", bg: "bg-blue-50" },
          { label: "AI-Driven Savings", val: "₹4.12 Cr", icon: <TrendingUp className="w-4 h-4"/>, color: "text-green-600", bg: "bg-green-50" },
          { label: "Demurrage Saved", val: "₹89 L", icon: <BarChart2 className="w-4 h-4"/>, color: "text-green-600", bg: "bg-green-50" },
          { label: "Cost Avoidance", val: "₹2.84 Cr", icon: <LineChart className="w-4 h-4"/>, color: "text-blue-600", bg: "bg-blue-50" },
          { label: "FreightIQ ROI", val: "14.8x", icon: <Percent className="w-4 h-4"/>, color: "text-amber-600", bg: "bg-amber-50" },
          { label: "Budget Variance", val: "-8.4%", icon: <TrendingUp className="w-4 h-4"/>, color: "text-green-600", bg: "bg-green-50" },
        ].map((kpi, i) => (
          <motion.div key={i} className="bg-white p-4 rounded-xl border border-gray-200 shadow-sm flex flex-col justify-between" title="Demo / Simulated KPI Metric">
            <div className="flex justify-between items-start mb-3">
              <div className="text-[10px] font-bold text-gray-500 uppercase tracking-widest leading-tight">{kpi.label}</div>
              <div className={`p-1.5 rounded-lg ${kpi.bg} ${kpi.color}`}>{kpi.icon}</div>
            </div>
            <div className="text-2xl font-black text-gray-900 leading-none mb-1">{kpi.val}</div>
            <div className="text-[9px] font-bold text-gray-400 uppercase tracking-widest">Demo Data</div>
          </motion.div>
        ))}
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-12 gap-6">
         <div className="xl:col-span-8 bg-white rounded-xl border border-gray-200 shadow-sm p-6 flex flex-col">
            <div className="flex justify-between items-start mb-6">
               <div>
                  <h2 className="text-sm font-black text-gray-900 uppercase tracking-widest mb-1">Cumulative Savings vs Unoptimized Benchmark</h2>
                  <p className="text-[11px] font-medium text-gray-500">FreightIQ Optimized Spend vs Baseline</p>
               </div>
               <div className="flex items-center gap-3 text-[9px] font-bold uppercase tracking-widest text-gray-500">
                  <div className="flex items-center gap-1.5"><div className="w-3 h-0.5 bg-gray-400"></div> Benchmark</div>
                  <div className="flex items-center gap-1.5"><div className="w-3 h-0.5 bg-green-500"></div> Actual Spend</div>
               </div>
            </div>
            
            <div className="flex-1 min-h-[300px] bg-gray-50 rounded-lg border border-gray-100 flex items-center justify-center relative overflow-hidden">
               {/* SVG Chart representation */}
               <div className="absolute left-10 right-0 top-6 bottom-10">
                 <svg className="w-full h-full overflow-visible" preserveAspectRatio="none" viewBox="0 0 100 100">
                    {/* Benchmark */}
                    <path d="M 0,90 L 33,60 L 66,35 L 100,10" fill="none" stroke="#9CA3AF" strokeWidth="2" strokeDasharray="4,4" />
                    {/* Actual */}
                    <path d="M 0,90 L 33,65 L 66,45 L 100,25" fill="none" stroke="#22C55E" strokeWidth="3" />
                    {/* Savings Gap shading */}
                    <path d="M 0,90 L 33,60 L 66,35 L 100,10 L 100,25 L 66,45 L 33,65 Z" fill="#22C55E" stroke="none" opacity="0.1" />
                 </svg>
                 <div className="absolute right-0 top-[15%] transform translate-x-2">
                   <span className="text-[10px] font-bold text-green-700 bg-green-50 px-1 border border-green-200 rounded">Gap: ₹4.12 Cr</span>
                 </div>
               </div>
               <div className="absolute bottom-4 w-full flex justify-around text-[10px] font-bold text-gray-400 pl-10 pr-4">
                  <span>Q1</span><span>Q2</span><span>Q3</span><span>Q4</span>
               </div>
            </div>
            
            <div className="mt-4 text-center">
               <p className="text-[11px] text-gray-600 font-medium">By Q4, actual spend tracking generated a cumulative savings gap of ₹4.12 Cr against the unoptimized spot market benchmark. <span className="font-bold text-gray-400 text-[10px] uppercase">(Simulated Data)</span></p>
            </div>
         </div>

         <div className="xl:col-span-4 space-y-6">
            <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-6">
               <h2 className="text-sm font-black text-gray-900 uppercase tracking-widest mb-4">FreightIQ ROI</h2>
               <div className="space-y-4">
                  <div className="flex justify-between items-center border-b border-gray-100 pb-2">
                     <span className="text-xs font-semibold text-gray-600">Technology Investment</span>
                     <span className="font-mono font-bold text-gray-900 text-sm">₹28 L</span>
                  </div>
                  <div className="flex justify-between items-center border-b border-gray-100 pb-2">
                     <span className="text-xs font-semibold text-gray-600">Savings Generated</span>
                     <span className="font-mono font-bold text-green-600 text-sm">₹4.12 Cr</span>
                  </div>
                  <div className="flex justify-between items-center border-b border-gray-100 pb-2">
                     <span className="text-xs font-semibold text-gray-600">Net Benefit</span>
                     <span className="font-mono font-black text-gray-900 text-lg">₹3.84 Cr</span>
                  </div>
                  <div className="flex justify-between items-center bg-gray-50 p-3 rounded-lg border border-gray-100">
                     <span className="text-xs font-black text-gray-900">ROI Multiple</span>
                     <span className="font-mono font-black text-amber-600 text-2xl">14.8x</span>
                  </div>
               </div>
               <div className="mt-3 text-right">
                  <span className="text-[9px] font-bold text-gray-400 uppercase tracking-widest">Demo Calculation</span>
               </div>
            </div>

            <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-6">
               <h2 className="text-sm font-black text-gray-900 uppercase tracking-widest mb-4">Savings Breakdown</h2>
               <div className="space-y-3">
                  <div className="bg-gray-50 p-3 rounded-lg">
                     <div className="flex justify-between text-xs mb-1">
                        <span className="font-bold text-gray-900">Spot Avoidance</span>
                        <span className="font-mono font-bold text-green-600">₹2.8 Cr</span>
                     </div>
                     <div className="w-full bg-gray-200 h-1.5 rounded-full overflow-hidden">
                        <div className="bg-green-500 h-full" style={{width: '68%'}}></div>
                     </div>
                  </div>
                  <div className="bg-gray-50 p-3 rounded-lg">
                     <div className="flex justify-between text-xs mb-1">
                        <span className="font-bold text-gray-900">Demurrage Reduction</span>
                        <span className="font-mono font-bold text-green-600">₹89 L</span>
                     </div>
                     <div className="w-full bg-gray-200 h-1.5 rounded-full overflow-hidden">
                        <div className="bg-green-500 h-full" style={{width: '21%'}}></div>
                     </div>
                  </div>
                  <div className="bg-gray-50 p-3 rounded-lg">
                     <div className="flex justify-between text-xs mb-1">
                        <span className="font-bold text-gray-900">Fuel Optimization</span>
                        <span className="font-mono font-bold text-green-600">₹43 L</span>
                     </div>
                     <div className="w-full bg-gray-200 h-1.5 rounded-full overflow-hidden">
                        <div className="bg-green-500 h-full" style={{width: '11%'}}></div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
    </motion.div>
  );
}
